#!/bin/bash

message="$@"

log() {
    logfile=~/.local/log/automate_zoom

    notify-send "$@"
    info="$date $@"

    echo "$info"
}

env DISPLAY=:1 zenity --question --timeout 60 --text="<big>$message</big>" --width=300
if [[ $? == 1 ]]; then
    log "Shutdown terminated"
else
    log "Shutdown initiated" 
fi

